"""create_file_upload_table

Revision ID: 42a4bf055c05
Revises: fd220b83bfd3
Create Date: 2026-02-10 23:05:19.067206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a4bf055c05'
down_revision: Union[str, Sequence[str], None] = 'fd220b83bfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('PNG', 'JPEG', 'PDF', 'CSV', 'EXCEL', 'DOCX', name='file_type'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'SUCCESS', 'PENDING', name='upload_status'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['accounts.id'], name=op.f('fk_file_upload_uploaded_by_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_upload'))
    )
    op.create_index(op.f('ix_file_upload_id'), 'file_upload', ['id'], unique=False)
    op.create_index(op.f('ix_file_upload_uploaded_by'), 'file_upload', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_upload_uploaded_by'), table_name='file_upload')
    op.drop_index(op.f('ix_file_upload_id'), table_name='file_upload')
    op.drop_table('file_upload')
    # ### end Alembic commands ###
